### ISSUE TITLE
Server Boosting Page not styled

### ISSUE THREAD

**Issue by zachjmurphy** [Slddev/ModernX-BDTheme#1]
![image](https://user-images.githubusercontent.com/78761892/144908904-37311711-f7fa-4cde-889a-0ccc887d7905.png)

**Comment by Slddev** [comment]
Thanks for informing me, Fixing right now.

**Comment by Slddev** [comment]
Fixed in [`f784279`](https://github.com/Slddev/ModernX-BDTheme/commit/f78427922e89472e97e51e2fd9c067824d017523).
